import 'package:json_annotation/json_annotation.dart';

part 'models.g.dart'; // File generated by build_runner

// -----------------------------------------------------------------
// 1. Xtream Codes Base Data Models
// -----------------------------------------------------------------

@JsonSerializable()
class UserInfo {
  @JsonKey(name: 'username')
  final String username;
  @JsonKey(name: 'password')
  final String password;
  @JsonKey(name: 'auth')
  final int authStatus;
  @JsonKey(name: 'status')
  final String status;
  @JsonKey(name: 'exp_date')
  final int? expDate;
  @JsonKey(name: 'max_connections')
  final int maxConnections;

  UserInfo({
    required this.username,
    required this.password,
    required this.authStatus,
    required this.status,
    this.expDate,
    required this.maxConnections,
  });

  factory UserInfo.fromJson(Map<String, dynamic> json) => _$UserInfoFromJson(json);
  Map<String, dynamic> toJson() => _$UserInfoToJson(this);
}

@JsonSerializable()
class LoginResponse {
  @JsonKey(name: 'user_info')
  final UserInfo? userInfo;
  @JsonKey(name: 'server_info')
  final Map<String, dynamic>? serverInfo;

  LoginResponse({this.userInfo, this.serverInfo});

  factory LoginResponse.fromJson(Map<String, dynamic> json) => _$LoginResponseFromJson(json);
}

// -----------------------------------------------------------------
// 2. Categories
// -----------------------------------------------------------------

@JsonSerializable()
class Category {
  @JsonKey(name: 'category_id')
  final String categoryId;
  @JsonKey(name: 'category_name')
  final String categoryName;

  Category({required this.categoryId, required this.categoryName});

  factory Category.fromJson(Map<String, dynamic> json) => _$CategoryFromJson(json);
}

// -----------------------------------------------------------------
// 3. Stream Item (Live, VOD, Series)
// -----------------------------------------------------------------

@JsonSerializable()
class StreamItem {
  @JsonKey(name: 'stream_id')
  final int? streamId;
  @JsonKey(name: 'series_id')
  final int? seriesId;
  @JsonKey(name: 'name')
  final String name;
  @JsonKey(name: 'stream_icon')
  final String? streamIcon;
  @JsonKey(name: 'cover')
  final String? cover;
  @JsonKey(name: 'category_id')
  final String categoryId;
  @JsonKey(name: 'container_extension')
  final String? containerExtension;
  @JsonKey(name: 'stream_type')
  final String? streamType;

  StreamItem({
    this.streamId,
    this.seriesId,
    required this.name,
    this.streamIcon,
    this.cover,
    required this.categoryId,
    this.containerExtension,
    this.streamType,
  });

  factory StreamItem.fromJson(Map<String, dynamic> json) => _$StreamItemFromJson(json);

  // Helper function to construct the playback URL
  String getStreamUrl(String host, String username, String password) {
    String type = streamType ?? 'movie';
    String id = (streamId ?? seriesId)?.toString() ?? '';
    String ext = containerExtension ?? (type == 'live' ? 'ts' : 'mp4');

    // Clean host from trailing slashes or API paths
    final cleanHost = host.replaceAll(RegExp(r'/(player_api\.php)?$'), '');

    return '$cleanHost/$type/$username/$password/$id.$ext';
  }
}
